plugins {
    id 'com.android.application'
}

android {
    namespace 'fun.nyama.tv'
    compileSdk 36

    defaultConfig {
        applicationId 'fun.nyama.plus'
        minSdk 24
        targetSdk 36
        versionCode 20
        versionName '1.0.18'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    def media3_version = '1.11.1'
    implementation "androidx.media3:media3-exoplayer:$media3_version"
    implementation "androidx.media3:media3-exoplayer-hls:$media3_version"
    implementation "androidx.media3:media3-exoplayer-dash:$media3_version"
    implementation "androidx.media3:media3-exoplayer-rtsp:$media3_version"
    implementation "androidx.media3:media3-ui:$media3_version"
    implementation 'androidx.work:work-runtime:2.12.0'
}
